#pragma once

#include <QDockWidget>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <string>
#include <nlohmann/json.hpp>

namespace microbotica::panels {

/// Graph inspector panel — read-only visualisation of MADDENING graph topology.
///
/// Renders the node/edge structure from graph.json (generated by MIME runner
/// on first launch via GraphManager.to_dict()). Nodes as rounded rectangles,
/// edges as arrows, back-edges as dashed arrows, coupling groups as shaded
/// bounding boxes.
///
/// Phase G feature — read-only in Phase 0. Interactive graph editing
/// (drag-and-drop node wiring) is a Phase 2+ feature.
class GraphInspectorPanel : public QDockWidget {
    Q_OBJECT

public:
    explicit GraphInspectorPanel(QWidget* parent = nullptr);

    /// Load graph topology from a JSON file (graph.json).
    bool loadFromFile(const std::string& json_path);

    /// Load graph topology from a JSON object.
    void loadFromJson(const nlohmann::json& graph);

    /// Clear the scene.
    void clear();

private Q_SLOTS:
    void zoomIn();
    void zoomOut();
    void zoomFit();
    void exportPng();

private:
    void layoutGraph(const nlohmann::json& graph);

    /// QGraphicsView subclass that zooms on the mouse wheel.
    class ZoomView;

    ZoomView* view_ = nullptr;
    QGraphicsScene* scene_ = nullptr;
};

} // namespace microbotica::panels
